sheets = {
    "General": ["seasonScale", "CO2Cap", "CO2Price"],
    "Sets": [
        "Nodes",
        "OffshoreNodes",
        "Horizon",
        "Storage",
        "Technology",
        "Generators",
        "LineType",
        "StorageOfNodes",
        "DirectionalLines",
        "LineTypeOfDirectionalLines",
        "GeneratorsOfNode",
        "GeneratorsOfTechnology",
        "Coords",
    ],
    "Generator": [
        "CapitalCosts",
        "FixedOMCosts",
        "VariableOMCosts",
        "FuelCosts",
        "CCSCostTSVariable",
        "Efficiency",
        "RefInitialCap",
        "ScaleFactorInitialCap",
        "InitialCapacity",
        "MaxBuiltCapacity",
        "MaxInstalledCapacity",
        "RampRate",
        "GeneratorTypeAvailability",
        "CO2Content",
        "Lifetime",
    ],
    "Node": ["ElectricAnnualDemand", "NodeLostLoadCost", "HydroGenMaxAnnualProduction"],
    "Transmission": [
        "lineEfficiency",
        "MaxBuiltCapacity",
        "Length",
        "TypeCapitalCost",
        "TypeFixedOMCost",
        "InitialCapacity",
        "MaxInstallCapacityRaw",
        "Lifetime",
    ],
    "Storage": [
        "InitialPowerCapacity",
        "PowerCapitalCost",
        "PowerFixedOMCost",
        "PowerMaxBuiltCapacity",
        "EnergyCapitalCost",
        "EnergyFixedOMCost",
        "EnergyInitialCapacity",
        "EnergyMaxBuiltCapacity",
        "EnergyMaxInstalledCapacity",
        "PowerMaxInstalledCapacity",
        "StorageInitialEnergyLevel",
        "StorageChargeEff",
        "StorageDischargeEff",
        "StoragePowToEnergy",
        "StorageBleedEfficiency",
        "Lifetime",
    ],
}
